
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftCOMMAASSIGN BOOLEAN COMMA IDENTIFIER LBRACKET NULL NUMBER RBRACKET SEMICOLON STRING TYPEstatement : declaration SEMICOLON\n                 | declarationdeclaration : TYPE IDENTIFIER ASSIGN arrayarray : LBRACKET elements_opt RBRACKETelements_opt : elements\n                    | elements COMMA\n                    | emptyelements : value\n                | elements COMMA valuevalue : NUMBER\n             | STRING\n             | BOOLEAN\n             | NULL\n             | arrayempty :'
    
_lr_action_items = {'TYPE':([0,],[3,]),'$end':([1,2,4,7,18,],[0,-2,-1,-3,-4,]),'SEMICOLON':([2,7,18,],[4,-3,-4,]),'IDENTIFIER':([3,],[5,]),'ASSIGN':([5,],[6,]),'LBRACKET':([6,8,19,],[8,8,8,]),'RBRACKET':([8,9,10,11,12,13,14,15,16,17,18,19,20,],[-15,18,-5,-7,-8,-10,-11,-12,-13,-14,-4,-6,-9,]),'NUMBER':([8,19,],[13,13,]),'STRING':([8,19,],[14,14,]),'BOOLEAN':([8,19,],[15,15,]),'NULL':([8,19,],[16,16,]),'COMMA':([10,12,13,14,15,16,17,18,20,],[19,-8,-10,-11,-12,-13,-14,-4,-9,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statement':([0,],[1,]),'declaration':([0,],[2,]),'array':([6,8,19,],[7,17,17,]),'elements_opt':([8,],[9,]),'elements':([8,],[10,]),'empty':([8,],[11,]),'value':([8,19,],[12,20,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> declaration SEMICOLON','statement',2,'p_statement','yacc_array.py',10),
  ('statement -> declaration','statement',1,'p_statement','yacc_array.py',11),
  ('declaration -> TYPE IDENTIFIER ASSIGN array','declaration',4,'p_declaration','yacc_array.py',15),
  ('array -> LBRACKET elements_opt RBRACKET','array',3,'p_array','yacc_array.py',19),
  ('elements_opt -> elements','elements_opt',1,'p_elements_opt','yacc_array.py',23),
  ('elements_opt -> elements COMMA','elements_opt',2,'p_elements_opt','yacc_array.py',24),
  ('elements_opt -> empty','elements_opt',1,'p_elements_opt','yacc_array.py',25),
  ('elements -> value','elements',1,'p_elements','yacc_array.py',28),
  ('elements -> elements COMMA value','elements',3,'p_elements','yacc_array.py',29),
  ('value -> NUMBER','value',1,'p_value','yacc_array.py',36),
  ('value -> STRING','value',1,'p_value','yacc_array.py',37),
  ('value -> BOOLEAN','value',1,'p_value','yacc_array.py',38),
  ('value -> NULL','value',1,'p_value','yacc_array.py',39),
  ('value -> array','value',1,'p_value','yacc_array.py',40),
  ('empty -> <empty>','empty',0,'p_empty','yacc_array.py',44),
]
